src/booking/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('book_car/<slug:slug>/', views.book_car, name='book'),
    path('book-room/<slug:slug>/', views.book_room, name='book-room'),
]

src/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


urlpatterns = [
    path('site-admin/', views.admin, name='system-admin'),
    path('', views.home_view, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('success/', views.success, name='success'),
    path('car-hiring/<pk>/', views.car_hiring_detail, name='hiring-detail'),
    path('page-not-found/', views.four_or_four_page, name='page-not-found'),
    path('car-hire-success/', views.car_hire_success, name='car-success'),
    path('room-book-success/', views.room_success, name='room-success'),
    path('gen-pdf/<pk>', views.generate_pdf, name='gen-pdf'),
    path('gen-pdf/<pk>', views.generate_pdf_room, name='gen-pdf-room'),
    path('car-hirings/', views.car_hirings, name='hirings'),
    path('room-bookings/', views.room_bookings, name='bookings'),
    path('room-bookings/<pk>/', views.room_booking_detail, name='booking-detail'),

    path('logout/', views.logout_view, name='logout'),
    path('login/', views.admin_login, name='login'),
]

src/server/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('services.urls')),
    path('', include('booking.urls')),
] 


if DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/services/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cars/', views.car_list, name='cars'),
    path('services/', views.service_list_view, name='services'),
    path('appartments/', views.appartment_list_view, name='appartments'),
    path('cars/<slug:slug>/', views.car_detail, name='car-detail'),
    path('rooms/<slug:slug>/', views.room_detail, name='room-detail')
]

src/booking/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models


from services.models import Car, Appartment


class CarHiring(models.Model):
    client_name = models.CharField(max_length=100)
    driving_licence_no = models.CharField(max_length=18)
    phone_number = models.CharField(max_length=18)
    vehicle = models.ForeignKey(Car, related_name='bookings', on_delete=models.CASCADE)
    pickup_location = models.CharField(max_length=200)
    pickup_date = models.CharField(blank=True, null=False, max_length=18)
    dropoff_date = models.CharField(blank=True, null=False, max_length=18)
    pickup_time = models.TimeField(auto_now=False)
    booked_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-booked_at',)

    def __str__(self):
        return self.client_name
    

class RoomBooking(models.Model):
    client_name = models.CharField(max_length=100)
    gov_id = models.CharField(max_length=18)
    phone_number = models.CharField(max_length=18)
    room = models.ForeignKey(Appartment, related_name='bookings', on_delete=models.CASCADE)
    checkin_date = models.CharField(blank=True, null=False, max_length=18)
    checkout_date = models.CharField(blank=True, null=False, max_length=18)
    booked_at = models.DateTimeField(auto_now_add=True)
    confirmed = models.BooleanField(default=False)

    class Meta:
        ordering = ('-booked_at',)

    def __str__(self):
        return self.client_name
    

src/services/models.py
from tabnanny import verbose
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.contrib.auth.models import User

# from .utils import slugify_instance_title

from django.core.files import File
from io import BytesIO
from PIL import Image


class Category(models.Model):
    category_name = models.CharField(max_length=25)
    passenger_capacity = models.IntegerField()
    laggage = models.CharField(max_length=100, null=True, blank=True)
    fuel_type = models.CharField(max_length=20, choices=(('p', 'Petro'), ('d', 'Diesel')), default='Petro')
    cost_per_day = models.DecimalField(max_digits=9, decimal_places=2)
    late_fee_per_hour = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=50, unique=True)
    
    class Meta:
        verbose_name_plural = 'Car Categories'
    
    def __str__(self):
        return self.category_name


class Location(models.Model):
    location_name = models.CharField(max_length=25)
    street = models.CharField(max_length=50)
    city = models.CharField(max_length=25)
    province = models.CharField(max_length=50)

    def __str__(self):
        return self.location_name
    

class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    thumbnail = models.ImageField(upload_to="Media/Services/Service-Thumbnails")
    slug = models.SlugField(blank=True, null=True, unique=True)
    


class Car(models.Model):
    category = models.ForeignKey(Category, related_name='cars', on_delete=models.CASCADE)
    brand_name = models.CharField(max_length=100, null=True, blank=True)
    registration_number = models.CharField(max_length=15)
    model_name = models.CharField(max_length=50)
    model_year = models.IntegerField()
    # mileage_count = models.IntegerField()
    transmission = models.CharField(choices=(('man', 'Manual'), ('auto', 'Automatic')), max_length=15)
    availability = models.BooleanField(default=True)
    thumbnail = models.ImageField(upload_to='services/uploads', blank=True, null=True)
    image_thumbnail = models.ImageField(upload_to='services/uploads', blank=True, null=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=50, unique=True)
    registered_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('-registered_at',)
    
    def __str__(self):
        return self.model_name

    def get_image_thumbnail(self):
        if self.image_thumbnail:
            return self.image_thumbnail
        else:
            if self.thumbnail:
                self.image_thumbnail = self.make_image_thumbnail(self.thumbnail)
                self.save()

                return self.image_thumbnail.url
            else:
                return 'https://via.placeholder.com/240x240x.jpg'

    def make_image_thumbnail(self, thumbnail, size=(300, 300)):
        img = Image.open(thumbnail)
        img.convert('RGB')
        img.thumbnail(size)

        thumb_io = BytesIO()
        img.save(thumb_io, 'JPEG', quality=85)
        name = thumbnail.name.replace('services/uploads/', '')
        image_thumbnail = File(thumb_io, name=name)

        return image_thumbnail


class ApartmentCategory(models.Model):
    category_name = models.CharField(max_length=80, choices=(('spe', 'Special'), ('reg', 'Regular'), ('vip', 'VIP')), default='VIP')
    # checking_out_time = models.TimeField(auto_now_add=False)
    slug = models.SlugField(max_length=50, unique=True, blank=True, null=True)
    
    class Meta:
        verbose_name_plural = 'Appartment Categories'
    
    def __str__(self):
        return self.category_name


class Appartment(models.Model):
    category = models.ForeignKey(ApartmentCategory, related_name='rooms', on_delete=models.CASCADE)
    appartment_name = models.CharField(max_length=200)
    bed_type = models.CharField(max_length=20, choices=(('sin', 'Single'), ('dou', 'Double'), ('que', 'Queen'), ('kin', 'King')), default='Single')
    appartment_capacity = models.IntegerField()
    cost_per_night = models.DecimalField(max_digits=9, decimal_places=2)
    description = models.TextField(blank=True, null=True)
    thumbnail = models.ImageField(upload_to="Services/appartments-thumbnails/")
    picture1 = models.ImageField(upload_to="Services/appartments-thumbnails/", blank=True, null=True)
    picture2 = models.ImageField(upload_to="Services/appartments-thumbnails/", blank=True, null=True)
    picture3 = models.ImageField(upload_to="Services/appartments-thumbnails/", blank=True, null=True)
    slug = models.SlugField(max_length=50, unique=True, blank=True, null=True)
    availability = models.BooleanField(default=True)
    status = models.CharField(max_length=20, choices=(('booked', 'Booked'), ('available', 'Available')), default='Available')

    def __str__(self):
        return self.appartment_name
    

src/services/forms.py
from django import forms
from .models import Service, Car, Appartment



class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = '__all__'

src/booking/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse

from .models import CarHiring, RoomBooking
from services.models import Category, Car, Appartment


def book_car(request, slug):
    car = Car.objects.get(slug=slug)
    related_cars = Car.objects.all().filter(category=car.category)

    
    if request.method == 'POST':
        booking = CarHiring()

        booking.client_name = request.POST.get('client_name')
        booking.driving_licence_no = request.POST.get('driving_licence_no')
        booking.phone_number = request.POST.get('phone_number')
        booking.vehicle = car
        booking.pickup_location = request.POST.get('pickup_location')
        booking.pickup_date = request.POST.get('pickup_date')
        booking.dropoff_date = request.POST.get('dropoff_date')
        booking.pickup_time = request.POST.get('pickup_time')
        booking.save()

        return redirect('car-success')

    return render(request, 'booking.html', {'car':car, 'related_cars': related_cars})


def book_room(request, slug):
    room = Appartment.objects.get(slug=slug)

    if request.method == "POST":
        booking = RoomBooking()
        booking.client_name = request.POST.get('client_name')
        booking.gov_id = request.POST.get('gov_id')
        booking.phone_number = request.POST.get('phone_number')
        booking.room = room
        booking.checkin_date = request.POST.get('checkin_date')
        booking.checkout_date = request.POST.get('checkout_date')
        booking.room.status = "booked"
        booking.save()
        
        return redirect('room-success')
    template = 'book-appartment.html'

    context = {}
    return render(request, template, context)

src/services/views.py
from django.shortcuts import render, get_object_or_404, redirect
from services.models import Category, Car, Service, ApartmentCategory, Appartment
from django.utils.text import slugify


def car_list(request):
    template = 'car-list.html'
    cars = Car.objects.all()
    context = {'cars': cars}
    return render(request, template, context)


def car_detail(request, slug):
    try:
        car = Car.objects.get(slug=slug)
        related_cars = Car.objects.all().filter(category=car.category)
        template = 'car-single.html'
        context = {'car': car, 'related_cars': related_cars}
    except Car.DoesNotExist:
        return redirect('page-not-found')
    
    return render(request, template, context)


def service_list_view(request):
    services = Service.objects.all()

    context = { 'services': services }
    template = 'services.html'
    return render(request, template, context)


def appartment_list_view(request):
    template = 'appartments.html'

    appartments = Appartment.objects.all()
    vip_appartments = Appartment.objects.all().filter(category__category_name='vip')
    special_appartments = Appartment.objects.all().filter(category__category_name='spe')
    regular_appartments = Appartment.objects.all().filter(category__category_name='reg')
    context = {
        'appartments': appartments,
        'special_appartments': special_appartments,
        'vip_appartments': vip_appartments,
        'regular_appartments': regular_appartments
        }
    return render(request, template, context)


def room_detail(request, slug):
    try:
        room = Appartment.objects.get(slug=slug)
        template = 'room-detail.html'
        context = {'room': room,}
    except Appartment.DoesNotExist:

        return redirect('page-not-found')
    
    return render(request, template, context)



def add_service(request):
    if request.method == "POST":
        service = Service()
        service.name = request.POST.get('name')
        service.description = request.POST.get('description')

src/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} About |{% endblock %}
{% load humanize %}
{% block content %}
    
    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url({% static 'images/signing.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start">
          <div class="col-md-9 ftco-animate pb-5">
          	<p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>About us <i class="ion-ios-arrow-forward"></i></span></p>
            <h1 class="mb-3 bread">About Us</h1>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section ftco-about">
			<div class="container-fluid">
				<div class="row no-gutters">
					<div class="col-md-6 p-md-5 img img-2 d-flex justify-content-center align-items-center" style="background-image: url({% static 'images/signing.jpg' %});">
					</div>
					<div class="col-md-6 wrap-about ftco-animate">
	          <div class="heading-section heading-section-white pl-md-5">
	          	<span class="subheading">About us</span>
              {% for about in about %}
	            <h2 class="mb-4">{{about.header}}</h2>

	            {{about.company_about | linebreaks }}
              {% endfor %}
	          </div>
					</div>
				</div>
			</div>
		</section>

<section class="ftco-section testimony-section bg-light">
      <div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-7 text-center heading-section ftco-animate">
          	<span class="subheading">Testimonial</span>
            <h2 class="mb-3">Happy Clients</h2>
          </div>
        </div>
        <div class="row ftco-animate">
          <div class="col-md-12">
            <div class="carousel-testimony owl-carousel ftco-owl">
				{% if customer_reviews %}
				{% for review in customer_reviews%}
              <div class="item">
                <div class="testimony-wrap rounded text-center py-4 pb-5">
                  <div class="text pt-4">
                    <p class="mb-4">{{ review.comments}}</p>
                    <p class="name">{{ review.name }}</p>
                    <span class="position">{{ review.occupation }}</span>
                  </div>
                </div>
              </div>
			  {% endfor %}
			  {% endif %}
            </div>
          </div>
        </div>
      </div>
    </section>

  <section class="ftco-counter ftco-section img bg-light" id="section-counter">
			<div class="overlay"></div>
    	<div class="container">
    		<div class="row">
          <div class="col-md-6 col-lg-3 justify-content-center counter-wrap ftco-animate">
            <div class="block-18">
              <div class="text text-border d-flex align-items-center">
                <strong class="number" data-number="5">0</strong>
                <span>Year <br>Experienced</span>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-3 justify-content-center counter-wrap ftco-animate">
            <div class="block-18">
              <div class="text text-border d-flex align-items-center">
                <strong class="number" data-number="{{car_count|intcomma}}">0</strong>
                <span>Total <br>Cars</span>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-3 justify-content-center counter-wrap ftco-animate">
            <div class="block-18">
              <div class="text text-border d-flex align-items-center">
                <strong class="number" data-number="{{customer_count|intcomma}}">0</strong>
                <span>Happy <br>Customers</span>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-3 justify-content-center counter-wrap ftco-animate">
            <div class="block-18">
              <div class="text d-flex align-items-center">
                <strong class="number" data-number="1">0</strong>
                <span>Total <br>Branch</span>
              </div>
            </div>
          </div>
        </div>
    	</div>
    </section>	

    {% endblock %}

src/templates/admin.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Admin | {% endblock %}


{% block content %}
 <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url({% static 'images/admin.png' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start">
          <div class="col-md-9 ftco-animate pb-5">
          	<p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Adminstrator <i class="ion-ios-arrow-forward"></i></span></p>
            <h1 class="mb-3 bread">Adminstrator</h1>
          </div>
        </div>
      </div>
    </section>


<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Client Name</th>
      <th scope="col">Client Phone</th>
      <th scope="col">Pickup Date</th>
      <th scope="col">Pick up time</th>
      <th scope="col">Booked at</th>
      <th scope="col">Cost per day</th>
    </tr>
  </thead>
  <tbody>
    {% for hiring in car_hirings %}
    <tr>
      <th scope="row"><a href="{% url 'hiring-detail' hiring.pk %}">{{ forloop.counter }}</a></th>
      <td><a href="{% url 'hiring-detail' hiring.pk %}">{{ hiring.client_name }}</a></td>
      <td>{{ hiring.phone_number }}</td>
      <td>{{ hiring.pickup_date }}</td>
      <td>{{ hiring.pickup_time }}</td>
      <td>{{ hiring.booked_at }}</td>
      <td>K{{ hiring.vehicle.category.cost_per_day }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<p><a href="{% url 'hirings' %}" class="btn btn-primary py-3 px-4">See all Car Hire requests</a></p>


<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Client Name</th>
      <th scope="col">Client Phone</th>
      <th scope="col">Checkin Date</th>
      <th scope="col">Checkout Date</th>
      <th scope="col">Booked At</th>
      <th scope="col">Cost per day</th>
    </tr>
  </thead>
  <tbody>
    {% for booking in bookings %}
    <tr>
      <th scope="row"><a href="{% url 'booking-detail' booking.pk %}">{{ forloop.counter }}</a></th>
      <td><a href="{% url 'booking-detail' booking.pk %}">{{ booking.client_name }}</a></td>
      <td>{{ booking.phone_number }}</td>
      <td>{{ booking.checkin_date }}</td>
      <td>{{ booking.checkout_date }}</td>
      <td>{{ booking.booked_at }}</td>
      <td>K{{ booking.room.category.cost_per_night }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<p><a href="{% url 'bookings' %}" class="btn btn-primary py-3 px-4">See all Room Booking requests</a></p>

{% endblock %}

src/templates/car-list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Cars |{% endblock %}
{% block content %}
    
    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url({% static 'images/fleet.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start">
          <div class="col-md-9 ftco-animate pb-5">
          	<p class="breadcrumbs"><span class="mr-2 text-warning"><a href="{% url 'home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Cars <i class="ion-ios-arrow-forward"></i></span></p>
            <h1 class="mb-3 text-warning bread">Choose Your Car</h1>
          </div>
        </div>
      </div>
    </section>
		

		<section class="ftco-section bg-light">
    	<div class="container">
    		<div class="row">
				{% if cars %}
				{% for car in cars %}
    			<div class="col-md-4">
    				<div class="car-wrap rounded ftco-animate">
    					<div class="img rounded d-flex align-items-end" style="background-image: url({{car.thumbnail.url}});">
    					</div>
    					<div class="text">
    						<h2 class="mb-0"><a href="car-single.html">{{car.model_name}}</a></h2>
    						<div class="d-flex mb-3">
	    						<span class="cat">{{car.brand_name}}</span>
	    						<p class="price ml-auto">{{car.category.cost_per_day}} <span>/day</span></p>
    						</div>
    						<p class="d-flex mb-0 d-block"><a href="{% url 'book' car.slug %}" class="btn btn-primary py-2 mr-1">Book now</a> <a href="{% url 'car-detail' car.slug %}" class="btn btn-secondary py-2 ml-1">Details</a></p>
    					</div>
    				</div>
    			</div>
				{% endfor %}
				{% else %}
				<div class="text-center">No cars yet...</div>
				{% endif %}
    		</div>
          </div>
        </div>
    	</div>
    </section>
    

   {% endblock %}

src/templates/main.html
<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

src/templates/room-bookings.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Room Bookings | {% endblock %}


{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Client Name</th>
      <th scope="col">Client Phone</th>
      <th scope="col">Checkin Date</th>
      <th scope="col">Checkout Date</th>
      <th scope="col">Booked At</th>
      <th scope="col">Cost per day</th>
    </tr>
  </thead>
  <tbody>
    {% for booking in bookings %}
    <tr>
      <th scope="row"><a href="{% url 'booking-detail' booking.pk %}">{{ forloop.counter }}</a></th>
      <td><a href="{% url 'booking-detail' booking.pk %}">{{ booking.client_name }}</a></td>
      <td>{{ booking.phone_number }}</td>
      <td>{{ booking.checkin_date }}</td>
      <td>{{ booking.checkout_date }}</td>
      <td>{{ booking.booked_at }}</td>
      <td>K{{ booking.room.category.cost_per_night }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<p><a href="{% url 'system-admin' %}" class="btn btn-primary py-3 px-4"><<< Admin </a></p>

{% endblock %}

src/templates/room-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{room}} | {% endblock %}
{% block content %}
    
    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('{{room.thumbnail.url}}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start">
          <div class="col-md-9 ftco-animate pb-5">
          	<p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Room Details <i class="ion-ios-arrow-forward"></i></span></p>
            <h1 class="mb-3 bread">Room Details</h1>
          </div>
        </div>
      </div>
    </section>
		

		<section class="ftco-section ftco-car-details">
      <div class="container">
      	<div class="row justify-content-center">
      		<div class="col-md-12">
      			<div class="car-details">
      				<div class="img rounded" style="background-image: url({{room.thumbnail.url}});"></div>
      				<div class="text text-center">
      					<span class="subheading">Room No: {{room}}</span>
      					<h2>Room Type: {{room.category.get_category_name_display}}</h2>
      				</div>
      			</div>
      		</div>
      	</div>
      	<div class="row">
          <div class="col-md d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services">
              <div class="media-body py-md-4">
              	<div class="d-flex mb-3 align-items-center">
	              	<div class="icon d-flex align-items-center justify-content-center"><span class="flaticon-bed"></span></div>
	              	<div class="text">
		                <h3 class="heading mb-0 pl-3">
		                	Bed Type
		                	<span>{{room.bed_type}} Bed</span>
		                </h3>
	                </div>
                </div>
              </div>
            </div>      
          </div>
          <div class="col-md d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services">
              <div class="media-body py-md-4">
              	<div class="d-flex mb-3 align-items-center">
	              	<div class="icon d-flex align-items-center justify-content-center"><span class="flaticon-team"></span></div>
	              	<div class="text">
		                <h3 class="heading mb-0 pl-3">
		                	Capacity
		                	<span>{{room.appartment_capacity}} Adults</span>
		                </h3>
	                </div>
                </div>
              </div>
            </div>      
          </div>
          <div class="col-md d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services">
              <div class="media-body py-md-4">
              	<div class="d-flex mb-3 align-items-center">
	              	<div class="icon d-flex align-items-center justify-content-center"><span class="flaticon-money"></span></div>
	              	<div class="text">
		                <h3 class="heading mb-0 pl-3">
		                	Price
		                	<span>K {{ room.cost_per_night }} /night</span>
		                </h3>
	                </div>
                </div>
              </div>
            </div>      
          </div>
      	</div>
      	<div class="row">
      		<div class="col-md-12 pills">
						<div class="bd-example bd-example-tabs">
							<div class="d-flex justify-content-center">
							  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">

							    <li class="nav-item">
							      <a class="nav-link active" id="pills-description-tab" data-toggle="pill" href="#pills-description" role="tab" aria-controls="pills-description" aria-expanded="true">Description</a>
							    </li>
							  </ul>
							</div>

						  <div class="tab-content" id="pills-tabContent">
						    <div class="tab-pane fade show active" id="pills-description" role="tabpanel" aria-labelledby="pills-description-tab">
								<p>{{room.description}}</p>
						    </div>
						  </div>
						  <div class="d-flex justify-content-center">
							  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">

							    <li class="nav-item">
							      {% comment %} <a class="btn btn-primary rounded-pill px-5 text-white" href="{% url 'book' car.slug %}" aria-expanded="true">Book Now!</a> {% endcomment %}
							    </li>
							  </ul>
							</div>
						</div>
		      </div>
		</div>
      </div>
    </section>

    <section class="ftco-section pt-3 ftco-no-pt bg-light">
    	<div class="container">
    		<div class="row justify-content-center">
          <div class="col-md-12 heading-section text-center ftco-animate mb-5">
          	<span class="subheading">Extra Pictures</span>
            {% comment %} <h2 class="mb-2">Featured Vehicles</h2> {% endcomment %}
          </div>
        </div>
    		<div class="row">
    			<div class="col-md-12">
    				<div class="carousel-car owl-carousel">
    					<div class="item">
    						<div class="car-wrap rounded ftco-animate">
		    					<div class="img rounded d-flex align-items-end" style="background-image: url({{ room.picture1.url }});">
		    					</div>
		    					<div class="text">
		    						<div class="d-flex mb-3">
		    						</div>
		    					</div>
		    				</div>
    					</div>
    					<div class="item">
    						<div class="car-wrap rounded ftco-animate">
		    					<div class="img rounded d-flex align-items-end" style="background-image: url({{ room.picture3.url }});">
		    					</div>
		    					<div class="text">
		    						<div class="d-flex mb-3">
		    						</div>
		    					</div>
		    				</div>
    					</div>
    					<div class="item">
    						<div class="car-wrap rounded ftco-animate">
		    					<div class="img rounded d-flex align-items-end" style="background-image: url({{ room.picture2.url }});">
		    					</div>
		    					<div class="text">
		    						<div class="d-flex mb-3">
		    						</div>
		    					</div>
		    				</div>
    					</div>
              
    				</div>
            <li class="nav-item">
							  <a href="{% url 'book-room' room.slug %}" class="btn btn-primary rounded-pill px-5 text-white">Book Now</a>
							</li>
    			</div>
    		</div>
    	</div>
    </section>
    

    {% endblock %}